// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeqvOtfUD1smapsN9oddnpaUcAtt9Wl0M',
    appId: '1:722975099688:web:c8f4e69726e5c1167d1e1d',
    messagingSenderId: '722975099688',
    projectId: 'gym-app-19590',
    authDomain: 'gym-app-19590.firebaseapp.com',
    storageBucket: 'gym-app-19590.appspot.com',
    measurementId: 'G-BYMY4SQSM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2gUWTXA0d7gcEsXgOkvuHVhBEgfgFvwk',
    appId: '1:722975099688:android:e092a4410c3c70087d1e1d',
    messagingSenderId: '722975099688',
    projectId: 'gym-app-19590',
    storageBucket: 'gym-app-19590.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVEZ_9k2I4pER0DOampyi6-yCvCgibLw',
    appId: '1:722975099688:ios:e3225ec3ea1921697d1e1d',
    messagingSenderId: '722975099688',
    projectId: 'gym-app-19590',
    storageBucket: 'gym-app-19590.appspot.com',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVEZ_9k2I4pER0DOampyi6-yCvCgibLw',
    appId: '1:722975099688:ios:a8eb7fb9d5e276dd7d1e1d',
    messagingSenderId: '722975099688',
    projectId: 'gym-app-19590',
    storageBucket: 'gym-app-19590.appspot.com',
    iosBundleId: 'com.example.gymApp.RunnerTests',
  );
}
